---
services:
  kafka-1:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "9092:9092"
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    environment:
      ### REQUIRED
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      ### FAILS WITHOUT THESE
      CLUSTER_ID: 'snEqtedQR4-9lMvInatV6Q'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:29092,SASL_PLAINTEXT://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:PLAINTEXT' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,SASL_PLAINTEXT://0.0.0.0:9092' 
      ### ADDITIONAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      ### KAFKA_OPTS
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
  kafka-2:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - "9093:9093"
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    environment:
      ### REQUIRED
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      ### FAILS WITHOUT THESE
      CLUSTER_ID: 'snEqtedQR4-9lMvInatV6Q'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:29093,SASL_PLAINTEXT://localhost:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:PLAINTEXT' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-2:29093,SASL_PLAINTEXT://0.0.0.0:9093' 
      ### ADDITIONAL
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      ### KAFKA_OPTS
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
  kafka-3:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - "9094:9094"
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    environment:
      ### REQUIRED
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      ### FAILS WITHOUT THESE
      CLUSTER_ID: 'snEqtedQR4-9lMvInatV6Q'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-3:29094,SASL_PLAINTEXT://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:PLAINTEXT' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-3:29094,SASL_PLAINTEXT://0.0.0.0:9094' 
      ### ADDITIONAL
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      ### KAFKA_OPTS
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

