---
services:
  kafka-1:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-1
    container_name: kafka-1
    ports:
      - "9092:9092"
    volumes:
      - ./config/kafka_server_admin_jaas.conf:/etc/kafka/kafka_server_admin_jaas.conf
    environment:
      ### REQUIRED
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      ### FAILS WITHOUT THESE
      CLUSTER_ID: 'snEqtedQR4-9lMvInatV6Q'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-1:29092,SASL_PLAINTEXT://kafka-1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SASL_PLAINTEXT,PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,SASL_PLAINTEXT://0.0.0.0:9092' 
      ### ADDITIONAL
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      #KAFKA_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: OAUTHBEARER
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: 'User:admin'
      ### KAFKA_OPTS
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_admin_jaas.conf'
      ### LOGGING; for additonal options take a look at https://docs.confluent.io/platform/current/installation/docker/development.html#log-to-external-volumes
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"


  kafka-2:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-2
    container_name: kafka-2
    ports:
      - "9093:9093"
    volumes:
      - ./config/kafka_server_admin_jaas.conf:/etc/kafka/kafka_server_admin_jaas.conf
    environment:
      ### REQUIRED
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      ### FAILS WITHOUT THESE
      CLUSTER_ID: 'snEqtedQR4-9lMvInatV6Q'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-2:29093,SASL_PLAINTEXT://kafka-2:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SASL_PLAINTEXT,PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-2:29093,SASL_PLAINTEXT://0.0.0.0:9093' 
      ### ADDITIONAL
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: OAUTHBEARER
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: 'User:admin'
      ### KAFKA_OPTS
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_admin_jaas.conf'
      ### LOGGING; for additonal options take a look at https://docs.confluent.io/platform/current/installation/docker/development.html#log-to-external-volumes
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"     

  kafka-3:
    image: confluentinc/cp-kafka:7.5.1
    hostname: kafka-3
    container_name: kafka-3
    ports:
      - "9094:9094"
    volumes:
      - ./config/kafka_server_admin_jaas.conf:/etc/kafka/kafka_server_admin_jaas.conf
    environment:
      ### REQUIRED
      KAFKA_PROCESS_ROLES: 'broker'
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      ### FAILS WITHOUT THESE
      CLUSTER_ID: 'snEqtedQR4-9lMvInatV6Q'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-3:29094,SASL_PLAINTEXT://kafka-3:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SASL_PLAINTEXT,PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT' 
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-3:29094,SASL_PLAINTEXT://0.0.0.0:9094' 
      ### ADDITIONAL
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: OAUTHBEARER
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_OAUTHBEARER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: OAUTHBEARER
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: 'User:admin'
      ### KAFKA_OPTS
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_admin_jaas.conf'
      ### LOGGING; for additonal options take a look at https://docs.confluent.io/platform/current/installation/docker/development.html#log-to-external-volumes
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"

  kafka-security-manager:
    image: conduktor/kafka-security-manager:latest
    environment:
      KSM_READONLY: "false"
      AUTHORIZER_CLASS: io.conduktor.ksm.compat.AdminClientAuthorizer
      #AUTHORIZER_ZOOKEEPER_CONNECT: "zoo1:2181"
      # FILE:
      SOURCE_CLASS: "io.conduktor.ksm.source.FileSourceAcl"
      SOURCE_FILE_FILENAME: "acls/preprod/main.yml"
      
      ADMIN_CLIENT_BOOTSTRAP_SERVERS: kafka-1:9092
      ADMIN_CLIENT_SECURITY_PROTOCOL: SASL_PLAINTEXT
      ADMIN_CLIENT_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required unsecuredLoginStringClaim_sub="admin";'

      ADMIN_CLIENT_SASL_MECHANISM: OAUTHBEARER
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_client_admin_jaas.conf'
      # GITHUB:
#      SOURCE_CLASS: "io.conduktor.ksm.source.GitHubSourceAcl"
#      SOURCE_GITHUB_USER: "conduktor"
#      SOURCE_GITHUB_REPO: "kafka-security-manager-example"
#      SOURCE_GITHUB_FILEPATH: "acls.csv"

      # SOURCE ACLS FROM KAFKA INSTEAD
      # THIS WON't WORK WITH THIS DOCKER COMPOSE FILE AS IT
      # REQUIRES KAFKA TO BE CONFIGURED IN SECURED MODE
      # PR ACCEPTED :)
      
      # AUTHORIZER_CLASS: "io.conduktor.ksm.compat.AdminClientAuthorizer"
      # ADMIN_CLIENT_BOOTSTRAP_SERVERS: "kafka1:19092"
      # set ADMIN_CLIENT_SECURITY_PROTOCOL, ADMIN_CLIENT_SASL_JAAS_CONFIG, ADMIN_CLIENT_SASL_MECHANISM, ADMIN_CLIENT_SSL_KEY_PASSWORD, ADMIN_CLIENT_SSL_KEYSTORE_LOCATION, ADMIN_CLIENT_SSL_KEYSTORE_PASSWORD, ADMIN_CLIENT_SSL_TRUSTSTORE_LOCATION, ADMIN_CLIENT_SSL_TRUSTSTORE_PASSWORD for a secure Kafka setup
    volumes:
      - ${PWD}/acls/preprod:/opt/docker/acls/preprod:ro
      - ./config/admin.properties:/etc/kafka/admin.properties
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
