name: ACL PR workflow
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'acls/**'
      - '**'
    types: [ opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, dismissed]
permissions:
  contents: read  # This is required for actions/checkout

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: See if there is pending requests
      env: 
        GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GHA_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/hrvoje459/oauth-kafka/pulls/2/requested_reviewers

    - name: print ref
      run: |
        echo ${{ github.ref }} 
        echo ${{ github.event.pull_request.number }}
        echo ${{ github.event.number }} 
        echo ${{ github.event.issue.number }}

      ### use third or fourth option in api calls

  ksm-run:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        image: hrvoje45/custom-ksm:latest
        options: |
          --env KSM_READONLY=true \
          --env AUTHORIZER_CLASS=io.conduktor.ksm.compat.AdminClientAuthorizer \
          --env SOURCE_CLASS=io.conduktor.ksm.source.FileSourceAcl \
          --env SOURCE_FILE_FILENAME=/opt/docker/acls/preprod/main.yml \
          --env ADMIN_CLIENT_BOOTSTRAP_SERVERS=kafka-1.oauthkafka.xyz:9092 \
          --env ADMIN_CLIENT_SECURITY_PROTOCOL=SASL_SSL \
          --env ADMIN_CLIENT_SASL_LOGIN_CALLBACK_HANDLER_CLASS=org.example.KSMLoginHandler \
          --env ADMIN_CLIENT_SASL_MECHANISM=OAUTHBEARER \
          --env ADMIN_CLIENT_SASL_OAUTHBEARER_SUB_CLAIM_NAME=azp \
          --env ADMIN_CLIENT_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/client.truststore.p12 \
          --env ADMIN_CLIENT_SSL_TRUSTSTORE_PASSWORD=${{ secrets.TRUSTSTORE_PASSWORD }} \
          --env NOTIFICATION_CLASS=io.conduktor.ksm.notification.ConsoleJsonNotification \
          --env KSM_REFRESH_FREQUENCY_MS=-1 \
          --env TO_DO_FILE_DESTINATION=/opt/docker/bin/to_do.json \
          --env ADMIN_CLIENT_SASL_JAAS_CONFIG='org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId=${{ secrets.KSM_CLIENT_ID }} clientSecret=${{ secrets.KSM_CLIENT_SECRET }} keycloak_instance=${{ secrets.KEYCLOAK_URL }} scope=profile;' \
        #   -v ${PWD}/acls/preprod:/opt/docker/acls/preprod:ro
        #   -v ./certs/cert_authority/client.truststore.p12:/etc/kafka/secrets/client.truststore.p12
        run: /opt/docker/bin/kafka-security-manager
        
    