name: ACL PR workflow
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'acls/**'
    types: [opened, reopened, review_requested]

permissions:
  contents: read  # This is required for actions/checkout

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: See if there is pending requests
      env: 
        GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
      run: |
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GHA_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/hrvoje459/oauth-kafka/pulls/2/requested_reviewers